apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-cicd
  labels:
    app: jenkins-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-cicd
  template:
    metadata:
      labels:
        app: jenkins-cicd
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: jenkins-cicd
        image: shalinichandru/jenkins-cicd:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
