apiVersion: apps/v1
kind: Deployment
metadata:
  name: utube-model
  labels:
    app: utube-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: utube-model
  template:
    metadata:
      labels:
        app: utube-model
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: utube-model
        image: shalinichandru/utube-model:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
